# Generated by Django 5.2.13 on 2026-04-14 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_employees', models.IntegerField()),
                ('employees_change', models.CharField(blank=True, max_length=10)),
                ('active_today', models.IntegerField()),
                ('active_change', models.CharField(blank=True, max_length=10)),
                ('overtime_hours', models.IntegerField()),
                ('overtime_change', models.CharField(blank=True, max_length=10)),
                ('monthly_payroll', models.IntegerField()),
                ('payroll_change', models.CharField(blank=True, max_length=10)),
                ('branch_count', models.IntegerField()),
                ('branch_change', models.CharField(blank=True, max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
