# Generated by Django 5.2.13 on 2026-04-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_stats'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChartData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, unique=True)),
                ('chart_style', models.CharField(max_length=20)),
                ('labels', models.JSONField()),
                ('values', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='stats',
            name='active_change',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='active_today',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='branch_change',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='branch_count',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='employees_change',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='monthly_payroll',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='overtime_change',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='overtime_hours',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='payroll_change',
        ),
        migrations.RemoveField(
            model_name='stats',
            name='total_employees',
        ),
        migrations.AddField(
            model_name='stats',
            name='icon',
            field=models.CharField(default='temp', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='number',
            field=models.CharField(default='0', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stats',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stats',
            name='percent',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='stats',
            name='title',
            field=models.CharField(default='Test', max_length=100),
            preserve_default=False,
        ),
    ]
