# Generated by Django 5.2.13 on 2026-04-14 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_chartdata_remove_stats_active_change_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chartdata',
            name='labels',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='chartdata',
            name='values',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
