# Generated by Django 5.2.13 on 2026-04-14 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_plan_planfeature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='button_text',
        ),
    ]
