# Generated by Django 5.2.13 on 2026-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_cookiepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='content_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='title_ms',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='cookiepolicy',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='description_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_ms',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_ru',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='planfeature',
            name='text_uz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='privacypolicy',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='percent_en',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='percent_ms',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='percent_ru',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='percent_uz',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='stats',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content_ms',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='content_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='title_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='title_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='title_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='termsofservice',
            name='title_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
