# Generated by Django 5.2.13 on 2026-04-15 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_card_description_en_card_description_ms_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name_ms',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name_uz',
        ),
        migrations.AlterField(
            model_name='plan',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_ms',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='description_uz',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
