# Generated by Django 5.2.13 on 2026-04-16 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_remove_plan_name_en_remove_plan_name_ms_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='price_en',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_ms',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_ru',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='price_uz',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
