# Generated by Django 5.2.13 on 2026-04-16 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_plan_price_en_plan_price_ms_plan_price_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ms',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='plan',
            name='name_uz',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
